### ISSUE TITLE
Problems with the Gradle-Wrapper

### ISSUE THREAD

**Issue by debian0501** [pysaumont/fpinkotlin#3]
With the commited ( fpinkotlin/fpinkotlin-parent/gradle/wrapper/gradle-wrapper.properties
) version 2.2.1 of gradle-wrapper I get the following error if I try to build the project:
* What went wrong:
A problem occurred configuring root project 'fpinkotlin-parent'.
> Failed to notify project evaluation listener.
   > org.gradle.api.Project.getPluginManager()Lorg/gradle/api/plugins/PluginManager;
   > org.gradle.api.Project.getPluginManager()Lorg/gradle/api/plugins/PluginManager;

If I updated the version to 4.6 everything works fine

**Comment by pysaumont** [comment]
Hi,

I have updated the wrapper to 4.6 a few days ago.

**Comment by debian0501** [comment]
Hi, but only in the root directory. There is also a gradle-wrapper.proterties in the fpinkotlin-parent directory and this is still at version 2.2.1

**Comment by pysaumont** [comment]
OK. Should be fixed now.

**Comment by debian0501** [comment]
Thanks
